server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=MusicAppDB;encrypt=false
    username: sa
    password: admin1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  security:
    user:
      name: admin
      password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

logging:
  level:
    org.hibernate.SQL: DEBUG