server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=MusicApp;encrypt=false
    username: SA
    password: MyStrongPass123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  security:
    user:
      name: admin
      password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    enabled: true

h2:
  console:
    enabled: false
